language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - TM4B_API_KEY=notARealSecretKey

before_install:
  - composer self-update

install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist

script: phpunit --coverage-text