language: php

php:
  - 7.0

env:
  - TM4B_API_KEY=notARealSecretKey

before_script:
  - composer install

script: ./vendor/bin/phpunit -v --configuration ./phpunit.xml.dist

cache:
  directories:
    - vendor