language: php

php:
  - 7.0

env:
  - TM4B_API_KEY=notARealSecretKey

before_script:
  - mv .env.sample .env
  - composer install --no-interaction --optimize-autoloader

script: ./vendor/bin/phpunit -v --configuration ./phpunit.xml.dist

cache:
  directories:
    - vendor